version: '3.9'
services:
  image_service:
    build: ./image_service
    ports:
      - "5001:5000"

  sensor_service:
    build: ./sensor_service
    ports:
      - "5000:5000"

  notify_service:
    build: ./notify_service
    ports:
      - "5002:5000"
